version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3002:3000"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_DATABASE=condominium
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./uploads:/usr/src/app/uploads
  #     - ./bills:/usr/src/app/bills
  #     - ./temp:/usr/src/app/temp

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=condominium
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 